package it.unibas.instcompview.view;

import bart.comparison.ValueMappings;

/**
 *
 * @author aurelio.sofia
 */
public class KeyValueMappingPanel extends javax.swing.JPanel {
    
    private ValueMappings valueMappings;
    private KeyValueMappingTableModel left;
    private KeyValueMappingTableModel right;
    /**
     * Creates new form KeyValueMappingPanel
     */
    public KeyValueMappingPanel(ValueMappings valueMappings) {
        this.valueMappings = valueMappings;
        initComponents();
        initTables();
    }
    
    private void initTables() {
        left = new KeyValueMappingTableModel(valueMappings.getLeftToRightValueMapping());
        this.leftTable.setModel(left);
        right = new KeyValueMappingTableModel(valueMappings.getRightToLeftValueMapping());
        this.rightTable.setModel(right);
    }
    
    public void updateTable(){
        left.updateTable();
        right.updateTable();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        leftScrollPane = new javax.swing.JScrollPane();
        leftTable = new javax.swing.JTable();
        rightScrollPane = new javax.swing.JScrollPane();
        rightTable = new javax.swing.JTable();
        leftTableLabel = new javax.swing.JLabel();
        rightTableLabel = new javax.swing.JLabel();

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        leftTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 128, 128)));
        leftTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        leftTable.getTableHeader().setReorderingAllowed(false);
        leftScrollPane.setViewportView(leftTable);
        if (leftTable.getColumnModel().getColumnCount() > 0) {
            leftTable.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(KeyValueMappingPanel.class, "KeyValueMappingPanel.rightTable.columnModel.title0")); // NOI18N
            leftTable.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(KeyValueMappingPanel.class, "KeyValueMappingPanel.rightTable.columnModel.title1")); // NOI18N
        }

        rightTable.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 165, 0)));
        rightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        rightTable.getTableHeader().setReorderingAllowed(false);
        rightScrollPane.setViewportView(rightTable);
        if (rightTable.getColumnModel().getColumnCount() > 0) {
            rightTable.getColumnModel().getColumn(0).setHeaderValue(org.openide.util.NbBundle.getMessage(KeyValueMappingPanel.class, "KeyValueMappingPanel.rightTable.columnModel.title0")); // NOI18N
            rightTable.getColumnModel().getColumn(1).setHeaderValue(org.openide.util.NbBundle.getMessage(KeyValueMappingPanel.class, "KeyValueMappingPanel.rightTable.columnModel.title1")); // NOI18N
        }

        leftTableLabel.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        leftTableLabel.setForeground(new java.awt.Color(0, 128, 128));
        org.openide.awt.Mnemonics.setLocalizedText(leftTableLabel, org.openide.util.NbBundle.getMessage(KeyValueMappingPanel.class, "KeyValueMappingPanel.leftTableLabel.text")); // NOI18N

        rightTableLabel.setFont(new java.awt.Font("Ubuntu", 3, 18)); // NOI18N
        rightTableLabel.setForeground(new java.awt.Color(255, 165, 0));
        rightTableLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        org.openide.awt.Mnemonics.setLocalizedText(rightTableLabel, org.openide.util.NbBundle.getMessage(KeyValueMappingPanel.class, "KeyValueMappingPanel.rightTableLabel.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 199, Short.MAX_VALUE)
                        .addComponent(leftTableLabel))
                    .addComponent(leftScrollPane, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rightScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                    .addComponent(rightTableLabel))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftTableLabel)
                    .addComponent(rightTableLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rightScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(leftScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JScrollPane leftScrollPane;
    private javax.swing.JTable leftTable;
    private javax.swing.JLabel leftTableLabel;
    private javax.swing.JScrollPane rightScrollPane;
    private javax.swing.JTable rightTable;
    private javax.swing.JLabel rightTableLabel;
    // End of variables declaration//GEN-END:variables

    
}
